package com.demo.springboot.domain.master;

import java.io.Serializable;

public class Provincial implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column provincial.pid
     *
     * @mbggenerated
     */
    private Integer pid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column provincial.Provincial
     *
     * @mbggenerated
     */
    private String provincial;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table provincial
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column provincial.pid
     *
     * @return the value of provincial.pid
     *
     * @mbggenerated
     */
    public Integer getPid() {
        return pid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column provincial.pid
     *
     * @param pid the value for provincial.pid
     *
     * @mbggenerated
     */
    public void setPid(Integer pid) {
        this.pid = pid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column provincial.Provincial
     *
     * @return the value of provincial.Provincial
     *
     * @mbggenerated
     */
    public String getProvincial() {
        return provincial;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column provincial.Provincial
     *
     * @param provincial the value for provincial.Provincial
     *
     * @mbggenerated
     */
    public void setProvincial(String provincial) {
        this.provincial = provincial == null ? null : provincial.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table provincial
     *
     * @mbggenerated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        Provincial other = (Provincial) that;
        return (this.getPid() == null ? other.getPid() == null : this.getPid().equals(other.getPid()))
            && (this.getProvincial() == null ? other.getProvincial() == null : this.getProvincial().equals(other.getProvincial()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table provincial
     *
     * @mbggenerated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getPid() == null) ? 0 : getPid().hashCode());
        result = prime * result + ((getProvincial() == null) ? 0 : getProvincial().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table provincial
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", pid=").append(pid);
        sb.append(", provincial=").append(provincial);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}