package com.demo.springboot.mapper.master;

import com.demo.springboot.domain.master.Provincial;

public interface ProvincialMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table provincial
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer pid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table provincial
     *
     * @mbggenerated
     */
    int insert(Provincial record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table provincial
     *
     * @mbggenerated
     */
    int insertSelective(Provincial record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table provincial
     *
     * @mbggenerated
     */
    Provincial selectByPrimaryKey(Integer pid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table provincial
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Provincial record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table provincial
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Provincial record);
}